### PR TITLE
bins aligned per-event

### LINKED ISSUE #43: improving precision of event rasters
The method of generating the rasters strikes me as incredibly imprecise. Please correct me if my understanding of the algorithm is wrong.

We create a single `bins` vector that spans the spiketimes, then...

``` Python
# bin the spikes into time bins
spike_counts = np.histogram(self.spiketimes, bins)[0]

# bin the events into time bins
event_counts = np.histogram(selected_events, bins)[0]
event_bins = np.where(event_counts > 0)[0]

raster = np.array([(spike_counts[(i+window[0]/binsize): \
                                 (i+window[1]/binsize+1)]) \
                   for i in event_bins])
```

Spikes AND events are binned in this vector and the raster is built from the counts aligned to the bins that contain events.

This approach means that any spike that lands in the same bin as the event is counted in that bin, no matter whether it occurred before the event of after.

Further, if events are not regular, then sometimes the event will happen early in the bin and the bin will consist mostly of spikes that happen after the event and other times, visa versa.

I expected that a unique `bins` vector would be constructed for each event, spanning the window so that spikes were clearly assigned before or after the event.

### PR DESCRIPTION
**Pull request by neuromusic**
this fixes #43

### CODE REVIEW

**Comment by pavanramkumar** [comment]
thanks, super quick and neat! will test on our notebooks now and then merge if ok.

**Comment by neuromusic** [comment]
The x ticks and event line don't line up on plot_raster correctly with these changes to the raster array.

image

image

**Comment by hugoguh** [comment]
Nice work!
Yes, you just need to subtract `0.5` in these two lines:
`xtics_loc = [0-0.5, (-window[0])/binsize-0.5,
                    (window[1]-window[0])/binsize-0.5]`
`plt.axvline((-window[0])/binsize-0.5, color='r', linestyle='--‘)`

**Comment by hugoguh** [comment]
Note that the event will always be at the edge of a bin. If there is a spike happening exactly at event time it will go to the bin that follows the event. This is probably only relevant when the event is the actual spike times of the neuron:
Here’s how it will look alined to spike_times and with a binsize of 10 ms:
screen shot 2016-06-28 at 16 33 14

It’s a simulated neuron:
screen shot 2016-06-28 at 16 39 55

**Comment by neuromusic** [comment]
sweet. added the offset & rebased

**Comment by hugoguh** [comment]
This rigorous way of doing is slower: 500ms vs 15s for 10K event times. We should in the near future either speed it up or have the initial not-that-rigorous way of doing it as a non-default option for faster data exploration.

**Comment by neuromusic** [comment]
yeah, the speed issue is something I've struggled with in other raster code I've written. I'm not sure what the right way to do this is. I suspect that one could use `np.searchsorted` to excise the spikes that are within the window before applying the histogram function and that might help a bit.

**Comment by hugoguh** [comment]
I’ll try `np.searchsorted` and some alternative to `np.histogram` to speed it up and/or add the old way as non-default option soon.

Unrelated to that (and because of the screenshot you sent), just in case you didn’t notice, you can use `xlim` and/or `ylim` in `plot_psth` to avoid having the `legend` over the psth curves. I’ve included that in the reaching notebook now, in the example of reward vs no reward.

**Comment by pavanramkumar** [comment]
Related: ```np.bincount``` seems like a fast alternative to ```np.histogram```
http://stackoverflow.com/questions/24516396/efficient-fast-numpy-histograms

**Comment by pavanramkumar** [comment]
Also, note we already have a ```numba``` dependency. If we want to consider accelerating existing pure python code, we can consider this option

**Pull request merged**
