### PR TITLE
Neural Coding Reward Example

### PR DESCRIPTION
**Pull request by timshell**
resubmission of neural coding reward example. From previous request:

The code to produce the graphs in Panels C & D seem to be working.

For Panels A & B, there are some errors.

1. I'm getting 1054 examples before matching, while the paper says there are only 691. I eliminated all trials with uncertainty not equal to 5 or 50. Is there something additional I need to do?

2. Despite starting with more trials before matching, I only end up with 22 afterwards as opposed to 210 in the paper.

Re: (2) this is my protocol (as what I understood from the paper).

For velocity, look at the times from 200ms post reward to the start of the next trial (i.e. when the cursor is moved to the center). The max velocity within this range must be between 11 and 16 cm/s.

For peak time, I added up all the rasters for each neuron in the given time window around the center target time. Then, I found which bin had the largest number of spikes and used that corresponding time to determine when the peak firing rate was. If it was 650 ms to 950 ms after the start of the trial, then they were good to go. Am I doing this incorrectly?

Note: the graphs before matching and after velocity matching look fine. It's only after the peak time matching that it goes awry. But also, I don't know why I'm getting a different number of initial trials to work with.

Any feedback would be helpful - thanks!

### CODE REVIEW

**Comment by pavanramkumar** [comment]
Hey @timshell I think I found the issue:

1. The experiment actually contains more data than we analyzed for this paper. In our full experiment, we varied not only the sensory reliability (which is column 3 of the trial table), we also varied the prior uncertainty (the distribution from which we draw the true location of the target on a given trial).

These two different prior uncertainty trials were administered in two distinct blocks. If you look in the `alldays` matlab struct, you will see that for the data from (monkey M, session 4) that you are analyzing, there are 3 elements in the struct. The first one is a regular center-out reach to a target with no uncertainty. The second and third ones are two different prior uncertainty blocks. For reasons that I'll leave out, we only used one of the two prior uncertainty conditions. In this case, it's element 2.

2. Let me make the matching protocol more explicit than in the Methods section. 
- For the peak velocity criterion, I select for max velocity magnitude, i.e. `np.sqrt(vx ** 2 + vy ** 2)` between [200, 1500] ms post-reward time.
- For the peak time criterion, I sub-sample trials with peak velocity occurring at between [550, 950] post-reward time.

Hope this helps you narrow it down!

**Comment by timshell** [comment]
@pavanramkumar 

The consecutive trials criterion ended up being the factor - I used this and got the 691 trials as mentioned in the paper. However, I only get this when I use all 3 elements on the alldays struct (not just the second).

I realized I was interpreting the peak time wrong. I fixed this and am now getting 223 trials after matching (with 691 before). The paper, however, goes from 691 to 210.

**Comment by pavanramkumar** [comment]
@timshell 

- You are right, my bad. It uses all elements in the `alldays`.
- I believe that the discrepancy between 210 and 223 comes from the fact that I applied the selection criteria (peak magnitude and peak time) after binning the velocity traces into 50-ms bins. Therefore what you are doing is more exact.

I looked at the notebook briefly and I'm happy to merge. Let me know if you're good and I can merge so that we get started on #60

**Comment by timshell** [comment]
@pavanramkumar Sounds good!

**Pull request merged**
