### PR TITLE
Flake8 Formatting

### PR DESCRIPTION
**Pull request by timshell**

### CODE REVIEW

**Comment by pavanramkumar** [comment]
@timshell thanks for this! `exclude` or `ignore` flags in a `setup.cfg` file may help you here. see: https://github.com/glm-tools/pyglmnet/blob/master/setup.cfg

**Comment by timshell** [comment]
@pavanramkumar perfect thanks! Is there any way I can check locally if it passes the TravisCI check? Or do I need to constantly commit and push?

**Comment by pavanramkumar** [comment]
@timshell if you install nose on your local machine and run tests you can check it locally.

```bash
pip install nose
pip install coverage
nosetests . --with-coverage
```

Same for `flake8`

**Comment by pavanramkumar** [comment]
@timshell i'm just leaving these here:
http://stackoverflow.com/questions/24343640/how-to-run-nosetests-without-showing-of-my-matplotlibs-graph
http://www.davidketcheson.info/2015/01/13/using_matplotlib_image_comparison.html

potentially useful to improve coverage for the visualization functions while allowing `matplotlib` to work well with `travisCI`

**Comment by timshell** [comment]
not building properly because of some tiny flake stuff with STRF - should I remove this, reclone, and fix those as well?

**Comment by pavanramkumar** [comment]
oops. i had run `flake8` and found no issues for `strf.py`. what issues are you seeing? if it's easier, i can reopen my PR, make the fix and merge. let me know!

**Comment by pavanramkumar** [comment]
never mind, i'm looking at the travis build. i think i can fix the flake8 issues in a new PR. once i merge, we can restart the travis-ci build.

**Comment by pavanramkumar** [comment]
@timshell i rebuilt travis-ci and it passed! but coverage decreased. let me know if you want to work on testing `matplotlib` using `mock`. otherwise, this looks good to merge for me.

**Comment by timshell** [comment]
I tried using mock but it fails (though it works perfectly locally). I was trying to look at your code, and I saw you commented out your visualization function in your test code. Does it build when that line is uncommented?

**Comment by pavanramkumar** [comment]
good catch re. the commented line. 

i tried re-running `nosetests . --with-coverage` and it works fine on my local device. haven't yet tried it with travis.

this is probably a dependency for matplotlib or mock that we are overlooking, but i'm not quite sure.

if you can't find a simple fix, i'm happy to merge without mock and then add more tests in future PRs

**Comment by timshell** [comment]
reverted commits for a merge now since I can't find a quick fix. In the meantime, I'll be looking for a solution

**Comment by pavanramkumar** [comment]
very nice, merging!

**Pull request merged**
