### PR TITLE
added MANIFEST & absolute style paths. fixes #40

### LINKED ISSUE #40: spykes.mplstyle not found on import
``` python
from neurovis import NeuroVis
```

```
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-11-c37dd3c942ac> in <module>()
----> 1 from neurovis import NeuroVis

/usr/local/home/jkiggins/Code/spykes/neurovis/__init__.py in <module>()
----> 1 from .neurovis import NeuroVis
      2 __version__ = '0.1.dev'

/usr/local/home/jkiggins/Code/spykes/neurovis/neurovis.py in <module>()
      2 import matplotlib.pyplot as plt
      3 
----> 4 plt.style.use('../mpl_styles/spykes.mplstyle')
      5 
      6 

/home/jkiggins/envs/jkiggins/lib/python2.7/site-packages/matplotlib/style/core.pyc in use(style)
     88                        "not a valid URL or path. See `style.available` for "
     89                        "list of available styles.")
---> 90                 raise IOError(msg % style)
     91 
     92 

IOError: '../mpl_styles/spykes.mplstyle' not found in the style library and input is not a valid URL or path. See `style.available` for list of available styles.
```

### PR DESCRIPTION
**Pull request by neuromusic**
this works with `pip install -e ./` but not with a vanilla pip install

### CODE REVIEW

**Comment by pavanramkumar** [comment]
Hey @neuromusic this is neat, thanks! 

Question: 
It works well if we run ```python setup.py install``` as well as with ```pip install -e ./```

Can you explain why we need MANIFEST.in?

**Comment by pavanramkumar** [comment]
P.S. Package still has moving parts! So, we're suggesting that users clone the latest repo for now. Once we have a stable release, we can make it work with vanilla ```pip install```

**Comment by neuromusic** [comment]
I suppose by vanilla, I just mean w/o using `-e`... `pip install ./` which moves everything into the `site-packages` folder rather than using the local files when importing the package. By default, setuptools etc skips non-py files in this process.

To be honest, I haven't completely wrapped my head around the best way to get setuptools to install these files properly. My understanding is that `MANIFEST.in` is one way to do this, but it doesn't seem to be working here (I think because the `mpl_styles` folder is not inside of either of the packages).

**Comment by pavanramkumar** [comment]
Understood re. `pip install`. If you can remove the `MANIFEST.in` file in a new commit, I can merge this PR

**Comment by neuromusic** [comment]
done. partially fixes #40

**Comment by pavanramkumar** [comment]
thanks!

**Pull request merged**
